doctrine:
    dbal:
        types:
            datetime: TS\DoctrineExtensions\DBAL\FixedDbTimezone\DateTimeType
            datetime_immutable: TS\DoctrineExtensions\DBAL\FixedDbTimezone\DateTimeImmutableType
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_mapping: true
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        default_entity_manager: default
#                url: "mysql://app:app@db:3306/app?serverVersion=mariadb-10.6.4"
                # "MultipleActiveResultSets", "application_name", "auto_commit", "charset", "connectstring", "dbname", "dbname_suffix", "default_dbnam
                # e", "default_table_options", "driver", "driver_class", "host", "instancename", "keep_replica", "keep_slave", "logging", "mapping_types", "memory", "options", "override_url", "password", "path", "persistent", "platform_service",
                # "pooled", "port", "profiling", "profiling_collect_backtrace", "profiling_collect_schema_errors", "protocol", "replicas", "schema_filter", "server", "server_version", "service", "servicename", "sessionMode", "shard_choser", "shar
                # d_choser_service", "shard_manager_class", "shards", "slaves", "sslcert", "sslcrl", "sslkey", "sslmode", "sslrootcert", "unix_socket", "url", "use_savepoints", "user", "wrapper_class".
                # pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, drizzle_pdo_mysql, sqlanywhere, sqlsrv
#                driver: pdo_mysql
#                server_version: 'mariadb-10.6.4'
#                host: localhost
#                port: 3306
#                dbname: app
#                charset: 'utf8mb4'
#                user: app
#                password: app
#                unix_socket: '/run/mysqld/mysqld.sock'
                 # pdo_mysql, pdo_sqlite, pdo_pgsql, pdo_oci, oci8, ibm_db2, pdo_sqlsrv, mysqli, drizzle_pdo_mysql, sqlanywhere, sqlsrv
#                server_version: 'mariadb-10.6.4'
#                host: localhost
#                port: 3306
#                dbname: app
#                charset: utf8mb4
#                user: app
#                password: app
#                default_table_options:
#                    charset: 'utf8'
#                    collate: 'utf8_unicode_ci'
#                path: ~
#                memory: ~
#                mapping_types:
#                    bit: boolean
#                    tsvector: string
#                    name: [ ]
#                url: '%env(resolve:DATABASE_URL)%'
#                unix_socket: '/run/mysqld/mysqld.sock'
#                persistent: ~
#                protocol: ~
#                service: ~
#                sessionMode: ~
#                pooled: ~
#                MultipleActiveResultSets: ~
#                platform_service: ~
#                logging: '%kernel.debug%'
#                profiling: '%kernel.debug%'
#                driver_class: ~
#                wrapper_class: ~
#                keep_slave: false
#                options:
#                    key: [ ]
#                slaves:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
#    orm:
#        auto_mapping: true
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App
#        default_entity_manager: default
#        proxy_namespace: Proxies
#        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
#        metadata_cache_driver: apc
#        query_cache_driver:
#            type: service
#            id: my_doctrine_common_cache_service
#        result_cache_driver:
#            type: memcache
#            host: localhost
#            port: 11211
#            instance_class: Memcache

#        auto_mapping: true
#        default_entity_manager:  ~
#        auto_generate_proxy_classes: false
#        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
#        proxy_namespace: Proxies
#        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#        class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
#        default_repository_class: Doctrine\ORM\EntityRepository
#        # search for the "ResolveTargetEntityListener" class for an article about this
#        resolve_target_entities: [ ]
#        entity_managers:
#            # A collection of different named entity managers (e.g. some_em, another_em)
#            some_em:
#                query_cache_driver:
#                    type: array # Required
#                    host: ~
#                    port: ~
#                    instance_class: ~
#                    class: ~
#                metadata_cache_driver:
#                    type: array # Required
#                    host: ~
#                    port: ~
#                    instance_class: ~
#                    class: ~
#                result_cache_driver:
#                    type: array # Required
#                    host: ~
#                    port: ~
#                    instance_class: ~
#                    class: ~
#                connection: ~
#                class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
#                default_repository_class: Doctrine\ORM\EntityRepository
#                auto_mapping: false
#                hydrators:
#                    # An array of hydrator names
#                    hydrator_name: [ ]
#                mappings:
#                    # An array of mappings, which may be a bundle name or something else
#                    mapping_name:
#                        mapping: true
#                        type: ~
#                        dir: ~
#                        alias: ~
#                        prefix: ~
#                        is_bundle: ~
#                dql:
#                    # a collection of string functions
#                    string_functions:
#                    # example
#                    # test_string: Acme\HelloBundle\DQL\StringFunction
#
#                    # a collection of numeric functions
#                    numeric_functions:
#                    # example
#                    # test_numeric: Acme\HelloBundle\DQL\NumericFunction
#
#                    # a collection of datetime functions
#                    datetime_functions:
#                    # example
#                    # test_datetime: Acme\HelloBundle\DQL\DatetimeFunction
#
#                # Register SQL Filters in the entity manager
#                filters:
#                    # An array of filters
#                    some_filter:
#                        class: ~ # Required
#                        enabled: false

