doctrine:
    dbal:
        default_connection: root
        types:
            datetime: TS\DoctrineExtensions\DBAL\FixedDbTimezone\DateTimeType
            datetime_immutable: TS\DoctrineExtensions\DBAL\FixedDbTimezone\DateTimeImmutableType
        connections:
            root:
                server_version: 'mariadb-10.6.4'
                driver: pdo_mysql
                host: db
                port: '3306'
                dbname: app
                override_url: true
                user: root
                password: root
                charset: 'utf8'
                mapping_types:
                    bit: boolean
                    tsvector: string
                url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
        default_repository_class: Doctrine\ORM\EntityRepository
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
