twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name:
            value: '%app.name%'
#    form_themes:
#        - form_div_layout.html.twig
    autoescape: name
    autoescape_service: null
    autoescape_service_method: null
#    cache: /app/var/cache/dev/twig
    charset: UTF-8
    paths: {  }
    date:
        format: 'F j, Y H:i'
        interval_format: '%d days'
        timezone: null
    number_format:
        decimals: 0
        decimal_point: .
        thousands_separator: ','



when@test:
    twig:
        strict_variables: true
