twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        app_name: '%kernel.environment%'

#when@test:
#    twig:
#        strict_variables: true
