debug:
    # Forwards VarDumper Data clones to a centralized server allowing to inspect dumps on CLI or in your browser.
    # See the "server:dump" command to start a new server.
    dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
    max_items: 2500
    min_depth: 1
    max_string_length: -1
    theme: dark

#debug:
#    dump_destination: 'tcp://%env(VAR_DUMPER_SERVER)%'
#    max_items: 2500
#    min_depth: 1
#    max_string_length: -1
#    theme: dark

