web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }


#web_profiler:
#    toolbar: true
#    intercept_redirects: false
#    excluded_ajax_paths: '^/((index|app(_[\w]+)?)\.php/)?_wdt'

