#index:
#    path: /
#    controller: App\Controller\DefaultController::index

root:
    path: /
    controller: App\Controller\IndexController::index


app:
    path: /application
    controller: App\Controller\AppController::index
    methods: [GET, HEAD, POST]
