# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
#imports:
#    - { resource: 'legacy_config.php' }
parameters:
    app.admin_email: 'something@example.com'
    app.enable_v2_protocol: true
    app.supported_locales: ['en', 'ru', 'ua']
    # binary content parameters (encode the contents with base64_encode())
#    app.some_parameter: !!binary VGhpcyBpcyBhIEJlbGwgY2hhciAH
    # PHP constants as parameter values
#    app.some_constant: !php/const JSON_ERROR_NONE
#    app.another_constant: !php/const App\Entity\App::MAX_ITEMS

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    Doctrine\Migrations\Version\DbalMigrationFactory: ~
#    App\Migrations\Factory\MigrationFactoryDecorator:
#        decorates: Doctrine\Migrations\Version\DbalMigrationFactory
#        arguments: [ '@App\Migrations\Factory\MigrationFactoryDecorator.inner', '@service_container' ]

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
