version: '3.3'

services:

    db:
        container_name: db
        image: mariadb:10.6.4
        ports:
            - "3306:3306"
        working_dir: /app
        volumes:
            - .dbdata:/var/lib/mysql
            - ..:/app
        env_file:
            - ../.env
        environment:
            DATABASE_URL: "mysql://app:app@db:3306/app?serverVersion=mariadb-10.6.4"
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_DATABASE: app
            MYSQL_PASSWORD: app
            MYSQL_USER: app
            MYSQL_DRIVER: pdo_mysql
        restart: always
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--password=root" ]
            interval: 15s
            timeout: 5s
            retries: 4

    php-fpm:
        container_name: php-fpm
        ports:
            - "9000:9000"
        build:
            context: ./php-fpm
            dockerfile: ./Dockerfile
            args:
                env: dev
        working_dir: /app
        environment:
            DATABASE_TIMEZONE: UTC
        volumes:
            - ~/.composer/docker-cache/:/root/.composer:cached
            - ../:/app
        restart: always
        depends_on:
            - db
        logging:
            driver: 'json-file'
            options:
                max-size: '10M'
                max-file: '2'

    nginx:
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                env: dev
        env_file:
            - ../.env
        working_dir: /app
        volumes:
            - /var/log/nginx:/var/log/nginx/
            - ..:/app
            - /etc/nginx/ssl:/etc/nginx/ssl
        depends_on:
            - php-fpm
        restart: always

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.9.5-management
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: app
            RABBITMQ_DEFAULT_PASS: app
            RABBITMQ_DEFAULT_VHOST: /
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '2'
        restart: always

    redis:
        container_name: redis
        ports:
            - "49155:6379"
        image: redis:6.2.5-alpine
        working_dir: /app
        environment:
            REDIS_PASSWORD: app
            REDIS_VERSION: 6.2.5
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 1m45s
            timeout: 5s
            retries: 4
        restart: always

volumes:
    dbdata:
