version: "3"
services:

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    working_dir: /app
    links:
      - php_fpm


  db:
    image: mariadb:10
    container_name: db
    working_dir: /app
    volumes:
      - .db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    env_file:
      - ../.env


  php_fpm:
    build: php-fpm
    container_name: php_fpm
    working_dir: /app
    environment:
      - DATABASE_TIMEZONE=UTC
      - PHP_REDIS_SESSION_HOST=redis
    env_file:
      - ../.env
    depends_on:
      - db
      - redis


  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - ../.env


  rabbitmq:
    image: rabbitmq:3.9.5-management
    container_name: rabbitmq
    env_file:
      - ../.env
