version: "3"
services:

  nginx:
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        env: dev

  db:
    ports:
      - "3324:3324"
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping' ]

  rabbitmq:
    ports:
      - "15674:15674"
      - "5677:5677"
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]

  php_fpm:
    ports:
      - "127.0.0.1:80:80"
    restart: unless-stopped
    build:
      args:
        env: dev
    volumes:
      - ~/.composer/docker-cache/:/root/.composer:cached
      - ../:/app
    environment:
      PHP_IDE_CONFIG: "serverName=PHPSTORM"
      PHP_REDIS_SESSION_HOST: "redis"
    logging:
      driver: 'json-file'
      options:
        max-size: '1024k'
        max-file: '2'
