version: "3.3"

services:
    async_worker:
        build: cli
        working_dir: /app
        container_name: async_worker
        restart: unless-stopped
        volumes:
          - ..:/app
          - /var/log/app:/app/var/log
        command: php -d memory_limit=2048 bin/console messenger:consume async_priority_high --limit=12 -vvv
