version: '3.3'
services:

    nginx:
        container_name: nginx
        ports:
            - "80:8080"
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                env: dev
        networks:
            - app_network
        working_dir: /app
        volumes:
            - /var/log/nginx:/var/log/nginx/
#        depends_on:
#            - php-fpm



    db:
        container_name: db
        ports:
            - "3306:3306"
        image: mariadb:10.6.4
#        image: bitnami/mariadb:latest
        working_dir: /app
        networks:
             - app_network
#                ipv4_address: 172.17.0.4
        volumes:
            - .dbdata:/var/lib/mysql
        environment:
            HOSTNAME: localhost
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            ALLOW_EMPTY_PASSWORD: 'no'
            DATABASE_URL: "mysql://app:app@db:3306/app?serverVersion=mariadb-10.6.4"
            MYSQL_PASSWORD: app
            MYSQL_USER: app
            MYSQL_DRIVER: pdo_mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        healthcheck:
            test: [ 'CMD', 'mysqladmin ping -h db -u root --password=root' ]
            interval: 15s
            timeout: 5s
            retries: 6
        restart: always





    php-fpm:
        container_name: php-fpm
        ports:
            - "9000:9001"
        build: php-fpm
        networks:
            - app_network
        working_dir: /app
        volumes:
            - .dbdata:/var/lib/mysql
            - ~/.composer/docker-cache/:/root/.composer:cached
            - ../:/app
        environment:
            DATABASE_TIMEZONE: 'UTC'
#            PHP_REDIS_SESSION_HOST: redis
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '2'
        restart: always
        depends_on:
            - db






    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15673:15674"
            - "5677:5678"
        environment:
            RABBITMQ_DEFAULT_USER: 'app'
            RABBITMQ_DEFAULT_PASS: 'app'
            RABBITMQ_DEFAULT_VHOST: '/'
        networks:
            - app_network
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '2'
        restart: always





    redis:
        container_name: redis
        image: bitnami/redis:latest
        environment:
            REDIS_PASSWORD: app
        networks:
            - app_network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 2m15s
            timeout: 7s
            retries: 4
        restart: always



volumes:
    dbdata:
        driver: local
        external: false


networks:
    private_app_lan:
        driver: bridge

    app_network:
        driver: bridge
