version: '3.3'

services:


    nginx:
        container_name: nginx
        ports:
            - "8080:80"
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
            args:
                env: dev
        networks:
            - app-lan
        working_dir: /app
        volumes:
            - /var/log/nginx:/var/log/nginx/
#        depends_on:
#            - php-fpm



    db:
        container_name: db
        ports:
            - "3306:3306"
        image: mariadb:10.6.4
#        image: bitnami/mariadb:latest
        working_dir: /app
        networks:
             - app-lan
#                ipv4_address: 172.17.0.4
        volumes:
            - .dbdata:/var/lib/mysql
        environment:
            HOSTNAME: localhost
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
#            - DATABASE_URL="mysql://root:root@localhost:3306/app?serverVersion=mariadb-10.6.4"
            ALLOW_EMPTY_PASSWORD: 'no'
#            - MYSQL_PASSWORD=app
#            - MYSQL_USER=app
#            - MYSQL_DATABASE=app
#            DATABASE_URL: mysql://root:root@localhost:3306/app?serverVersion=mariadb-10.6.4
#            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: app
            MYSQL_USER: app
#            MYSQL_DATABASE: app
        restart: always
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        healthcheck:
            test: [ 'CMD', 'mysqladmin ping -h 127.0.0.1 -u root --password=root' ]
#            test: mysqladmin ping -h 127.0.0.1 -u root --password=root
#            test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
            interval: 15s
            timeout: 5s
            retries: 6


    php-fpm:
        container_name: php-fpm
        ports:
            - "9000:9001"
        build: php-fpm
        networks:
            - app-lan
        working_dir: /app
        volumes:
            - .dbdata:/var/lib/mysql
            - ~/.composer/docker-cache/:/root/.composer:cached
            - ../:/app
        environment:
            DATABASE_TIMEZONE: UTC
            PHP_REDIS_SESSION_HOST: redis
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '2'
        restart: on-failure
        depends_on:
            - db
#        link:
#            - db
#        env_file:
#            - ../.env



    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:latest # rabbitmq:3-management
        ports:
            - "15673:15674"
            - "5677:5678"
        environment:
            RABBITMQ_DEFAULT_USER: 'app'
            RABBITMQ_DEFAULT_PASS: 'app'
            RABBITMQ_DEFAULT_VHOST: '/'
        networks:
            - app-lan
        logging:
            driver: 'json-file'
            options:
                max-size: '1024k'
                max-file: '2'
#        restart: unless-stopped


    redis:
        container_name: redis
        image: bitnami/redis:latest
        environment:
            REDIS_PASSWORD: app
        networks:
            - app-lan
        volumes:
            - .redisdata:/bitnami/redis/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 2m15s
            timeout: 7s
            retries: 4


volumes:
    dbdata:
        driver: local
        external: false


networks:
    app-lan:
        driver: bridge
